### ISSUE TITLE
zimwriterfs fails to create the zim

### ISSUE THREAD

**Issue by LAfricain** [openzim/zim-tools#257]
When I try to create a new zim with my data, zimwriterfs fails to do it with this error:
```
...
Visiting directory ./data/catherine_sienne/Lettres
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./zimwriterfs.sh : ligne 2 : 19357 Abandon                 zimwriterfs --welcome=GraphoN_index.htm --favicon=Graphon.png --language=fra --description="Textes patristiques, du magistère, auteurs chrétiens ou en lien avec le christianisme" --creator="Moi" --publisher="moi" --title="GraphoN" -v ./data graphon_fr_all_2021-08.zim
```
Can you help me? I used zimwriterfs in march, and it worked fine.

**Comment by mgautierfr** [comment]
This is probably this issue (https://github.com/openzim/libzim/issues/578). It is fixed but not released yet.
You can use the zstd compression (`-z` option) which is not impacted by the bug (and you should use zstd compression as it is the new "standard" in libzim).

**Comment by LAfricain** [comment]
Hi, Thank you for the quick answer. It's working better, but, still fails with this error: 
```
terminate called after throwing an instance of 'Xapian::DatabaseError'
Abandon
```

**Comment by mgautierfr** [comment]
Have you deleted the temporary files created by the indexer (graphon_fr_all_2021-08.zim.idx*) ?
